#ifndef __rcbasic_edit_codeHint_window__
#define __rcbasic_edit_codeHint_window__

/**
@file
Subclass of rc_codeHint_window, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"
#include "rcbasic_symbol.h"

//// end generated include



/** Implementing rc_codeHint_window */
class rcbasic_edit_codeHint_window : public rc_codeHint_window
{
    private:
        wxString s_prefix;
        wxString s_name;
        wxArrayString s_args;
        int s_arg_num;

	protected:
		// Handlers for rc_codeHint_window events.
		void OnSetFocus( wxFocusEvent& event );
		void OnWindowResize( wxSizeEvent& event );
		void OnSetFocus_Doc( wxFocusEvent& event );
	public:
		/** Constructor */
		rcbasic_edit_codeHint_window( wxWindow* parent );
	//// end generated class members

	bool pointInPanel(wxPoint check_point);
	void updateDoc();

	void setCodeHint(int symbol_type, wxString symbol_name, wxArrayString symbol_args, int arg_num=-1);

    wxHtmlWindow* getHtmlWindow();

};

#endif // __rcbasic_edit_codeHint_window__
