#ifndef __rcbasic_edit_codeCompletion_window__
#define __rcbasic_edit_codeCompletion_window__

/**
@file
Subclass of rc_codeCompletion_window, which is generated by wxFormBuilder.
*/

#include <wx/wx.h>
#include "rcbasic_edit.h"
#include "rcbasic_symbol.h"

//// end generated include

/** Implementing rc_codeCompletion_window */
class rcbasic_edit_codeCompletion_window : public rc_codeCompletion_window
{
    private:
        bool show_comp_flag;
        bool dbl_click;

        bool resize_d;

        rc_codeComp_symbolDatabase* symbol_db;
        rc_codeComp_symbolDatabase* user_db;
        rc_udt_db* utype_db;

        bool use_udt_db;
        int utype_index;

	protected:
		// Handlers for rc_codeCompletion_window events.
		void OnSetFocus( wxFocusEvent& event );
		void OnWindowResize( wxSizeEvent& event );

		void OnSetFocus_ListBox( wxFocusEvent& event );
		void OnSetFocus_Doc( wxFocusEvent& event );

		void OnLeftDClick_ListBox( wxMouseEvent& event );
		void OnListBoxSelection( wxCommandEvent& event );

	public:
		/** Constructor */
		rcbasic_edit_codeCompletion_window( wxWindow* parent, rc_codeComp_symbolDatabase* s_db, rc_codeComp_symbolDatabase* u_db, rc_udt_db* udt_db, bool udt_flag, int udt_index );
	//// end generated class members

        void setCompList(wxArrayString cc_list);

        void setCompShow(bool flag);

        void forceResize();

        wxListBox* getListBox();
        wxHtmlWindow* getHtmlWindow();

        bool getDBLClick();
        void setDBLClick(bool flag);

        void updateDoc(bool is_udt, int udt_index);

        bool pointInPanel(wxPoint check_point);

};

#endif // __rcbasic_edit_codeCompletion_window__
