#ifndef __rcbasic_edit_codeCompletion_dialog__
#define __rcbasic_edit_codeCompletion_dialog__

/**
@file
Subclass of rc_codeCompletion_dialog, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"

//// end generated include

/** Implementing rc_codeCompletion_dialog */
class rcbasic_edit_codeCompletion_dialog : public rc_codeCompletion_dialog
{
	public:
		/** Constructor */
		rcbasic_edit_codeCompletion_dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __rcbasic_edit_codeCompletion_dialog__
