#ifndef __rcbasic_editrc_genKey_dialog__
#define __rcbasic_editrc_genKey_dialog__

/**
@file
Subclass of rc_genKey_dialog, which is generated by wxFormBuilder.
*/

#include "rcbasic_edit.h"
#include <wx/process.h>

//// end generated include

/** Implementing rc_genKey_dialog */
class rcbasic_editrc_genKey_dialog : public rc_genKey_dialog
{
    private:
        wxProcess* process;
        int pid;
        bool isRunning;
        wxFileName fname;
	protected:
		// Handlers for rc_genKey_dialog events.
		void onOKButtonClick( wxCommandEvent& event );
		void onCancelButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		rcbasic_editrc_genKey_dialog( wxWindow* parent );
	//// end generated class members

	void onKeyGenProcessTerminate( wxProcessEvent& event );

};

#endif // __rcbasic_editrc_genKey_dialog__
